### ISSUE TITLE
RMSD function

### ISSUE THREAD

**Issue by ralf-meyer** [hjkgrp/molSimplify#127]
The whole `rmsd.py` file is based on the implementation in the pypi package of the same name. Clorice noticed that the reordering of atoms using the Hungarian method yields unexpected results (larger RMSDs than before reordering). As far as I can tell the main reason is that the Hungarian algorithm is solely based on Cartesian distances of atoms without first aligning the two molecules. A possible solution might center and align the molecules using their principal axes of inertia first.

**Comment by aarongarrison** [comment]
I have implemented a new rmsd function, `align_rmsd` (in branch https://github.com/hjkgrp/molSimplify/tree/rmsd_inertia), which aligns the molecules based on their center of mass and their principal moments of inertia first, and then implements a reordering and then a rotation before computing the RMSD. This function also includes 180 degree rotations about each coordinate axis, as well as reflections about each coordinate plane (and the reflection across all three) - it thus is not good for chiral molecules but should work for everything else. This function is less efficient than the current `rigorous_rmsd`, but should be less prone to fall into local minima than that implementation, and thus be better for structures where the proper ordering is not known and initial alignment is expected to be poor.

The reason that `rigorous_rmsd` could result in higher RMSDs than before reordering is that, if two atoms were close in space in the initial structures, they would be assigned to one another for the alignment, which is not always correct. A particularly helpful example is a dummy trigonal bipyramidal structure, such as:
```
6

Fe 0 0 0
O  -0.5  0.866 0
O  -0.5 -0.866 0
O  1 0 0
O  0 0 0.8
O  0 0 -1
```

If this structure is rotated 180 degrees about the x-axis, it leads to the two axial ligands (the final two O's) being switched in their assignment, and so `rigorous_rmsd` increases the RMSD relative to no reordering. The `align_rmsd` function does not have this problem, although it does return a marginally higher RMSD compared to no reordering and no alignment (5.8e-14 for `align_rmsd` vs. 5.8e-17 with no reordering (and 0.64 for `rigorous_rmsd`)), which I think is attributable to numerical noise. A similar result is obtained on the minimal example, with 2e-15 for `align_rmsd`, 1.5e-16 for no reordering, and 0.12 for `rigorous_rmsd`.
