### ISSUE TITLE
Set custom data directory non interactively

### ISSUE THREAD

**Issue by nhadler** [hjkgrp/molSimplify#130]
Is there a way to set the custom data directory non-interactively? 

I'm trying to develop a package that uses molSimplify through the python API to generate catalyst structures on demand. I'm planning on including several custom ligands as part of this package and I'd prefer to be able to set their locations as part of a config file in the root of the package, rather than a user needing to type it into the command line or having to modify the dot file in their home directory. 

Ideally I'd like to be able to set this as a flag in the python API or a config file in the directory root.

Thanks!

**Comment by nhadler** [comment]
Hi @ralf-meyer 

That would work perfectly, it would be easy enough to pass along that flag each call.

**Comment by ralf-meyer** [comment]
@nhadler I have implemented a `custom_data_dir` option for the CLI and input file modes in PR #132. It will be part of the next release! Alternatively, this newest version allows you to set the path directly in the `globalvars` class before the calls to the python API:
```
from molSimplify.Classes.globalvars import globalvars
glob_vars = globalvars()
glob_vars.custom_path = "/path/to/your/data"
```

**Comment by nhadler** [comment]
@ralf-meyer Fantastic! That would work perfectly, especially the ease of just placing it as a globalvar. Thanks for the quick patch!
