### ISSUE TITLE
import openbabel" is deprecated

### ISSUE THREAD

**Issue by nhadler** [hjkgrp/molSimplify#148]
I'm not sure if this has been corrected for the next release, but I couldn't find an issue for it.

The method for import the openbabel method has changed and I get this error upon running molSimplify.

`warnings.warn('"import openbabel" is deprecated, instead use "from openbabel import openbabel"')`

**Comment by ralf-meyer** [comment]
@nhadler thank you for bringing this up. I fixed this in commit 30e533736dd05b1ac48af6451b84f563dbf61962 but forgot to merge it! Should be fixed now!
