### ISSUE TITLE
Fixing the RGen Function

### ISSUE THREAD

**Issue by ryanlewisshu** [hjkgrp/molSimplify#179]
Hi,

May I first of all thank the group for helping me download MolSimplify and getting it to work! As suggested to me, I have raised this to see if it would be possible to get the rgen function working again in the future please.

In our group we was originally going to use the rgen function to create a multitude of different catalyst structures which we could use high throughput DFT in order to build a dataset for an ML model we are planning to use. We still plan to use MolSimplify for this project and I want to thank your team for giving me a workaround to this issue. It would however, be great to see the rgen function working in the future as it would be a fantastic tool for a more effective workflow for a project like this.

Thank you again.

**Comment by gianmarco-terrones** [comment]
Hi Ryan, would these complexes all be octahedral, contain solely monodentate ligands, and have the same metal center? Or would they be more varied than that?

**Comment by ralf-meyer** [comment]
@ryanlewisshu Basic functionality of the RGen function should be restored thanks to PR #184 by @rolan701

**Comment by ryanlewisshu** [comment]
Thank you very much and apologies for my delay in response.

We would be using this to make basic trigonal planar compounds with varied ligands attached to them.
