### ISSUE TITLE
Randomize orientation of molecule on slab

### ISSUE THREAD

**Issue by chrisewolf** [hjkgrp/molSimplify#18]
Dear all,

I was reading through the manual but I am not sure if molsimplify can do the following:

I have a slab.xyz and a molecule.xyz. I want to place the molecule on the slab with a certain distance but randomize orientation (to generate a set of input files and sample the configuration space), e.g. lets say I want 1000 randomized positions where I keep the distance fixed but allow the molecule to move in x-y plane and rotate around its z axis (the molecule is planar and "long" in the z-direction, z being the surface normal).

can this be achieved with molsimplify?

Thanks in advance for your help!

Best,
Chris

**Comment by jpjanet** [comment]
Thanks for your question and apologies for the delay in getting back to you. 
The answer is ‘not directly’. By default, alignment is controlled to reduce steric hindrance and will be deterministic. However, we do support definition of custom angles in our input syntax. Consider the MnO5 example from our tutorial (you can get the files [here](https://hjkgrp.mit.edu/content/molsimplify-tutorial-2-slab-builder)). By using the following placement syntax, we can specify and angle between atoms 1 and 6 of the placed molecule and the x=y line in the in the surface plane to be 60 degrees:
```
-place_on_slab True
-unit_cell slab.xyz 
-cell_vector [[11.973, 0, 0], [0, 11.973000000000001, 0], [0, 0, 27.982]] 
-target_molecule mno5.xyz 
-surface_atom_type Pd 
-surface_atom_type Pd 
-align_method alignpair 
-object_align 6
-control_angle 60
-angle_control_partner 1
-angle_surface_axis [1,1]
-align_dist 2.1
```
Changing this to 30 gives a different placement, as shown by the green overlay in this picture:

![im](https://user-images.githubusercontent.com/13276185/51503166-92bb4080-1da7-11e9-9b46-bc5b114b7646.png)



If you randomly sampled angles and repeatedly called molSimplify, you could get something like you describe, especially if you also randomized the connection atom and distance to the surface. That said, all of the geometric functions for manipulation in molSimplify  are available as imports in python, so if you are comfortable with scripting you could start with a single configuration and very easily randomize the position and orientation of the absorbed species using the methods from [mol3D](https://github.com/hjkgrp/molSimplify/blob/master/molSimplify/Classes/mol3D.py) and [geometry](https://github.com/hjkgrp/molSimplify/blob/master/molSimplify/Scripts/geometry.py), e.g.  [rotate_around_axis](https://github.com/hjkgrp/molSimplify/blob/7d8eaa74231e244cceda689ee77038ad879ce463/molSimplify/Scripts/geometry.py#L438).  Feel free to email me if you have further questions and we can discuss a specific use case.
