### ISSUE TITLE
Strain rotation: AttributeError: 'OBAtom' object has no attribute 'atomicnum'

### ISSUE THREAD

**Issue by chrisewolf** [hjkgrp/molSimplify#19]
Dear all,

I am trying to align a "ligand" to hollow sites on an Ag(111) slab. To the best of my understanding this could be achieved by assigning each target ligand atom 3 Ag surface atoms. Now my ligand has to Fe (atom 39 and 40 in my xyz file) and I would like use

-object_align 39, 40

this however leads to a crash with the following error

> starting strain rotation
> 
>  begining distortion 
> Traceback (most recent call last):
>   File "/home/chris/miniconda2/envs/molSimplify/bin/molsimplify", line 11, in <module>
>     load_entry_point('molSimplify==1.2.7a0', 'console_scripts', 'molsimplify')()
>   File "/home/chris/miniconda2/envs/molSimplify/lib/python2.7/site-packages/molSimplify/__main__.py", line 152, in main
>     emsg = startgen(sys.argv,False,gui)
>   File "/home/chris/miniconda2/envs/molSimplify/lib/python2.7/site-packages/molSimplify/Scripts/generator.py", line 159, in startgen
>     emsg = slab_module_supervisor(args,rundir)
>   File "/home/chris/miniconda2/envs/molSimplify/lib/python2.7/site-packages/molSimplify/Scripts/cellbuilder.py", line 1367, in slab_module_supervisor
>     weighting_method = 'linear',weight=weight, masklength = num_surface_atoms, surface_atom_ind = surface_atom_ind,debug=debug)
>   File "/home/chris/miniconda2/envs/molSimplify/lib/python2.7/site-packages/molSimplify/Scripts/cellbuilder.py", line 798, in molecule_placement_supervisor
>     loaded_cell = combine_multi_aligned_payload_with_cell(loaded_cell,super_cell_vector,payload,cand_list,sites_list,align_dist,duplicate,control_angle,debug)
>   File "/home/chris/miniconda2/envs/molSimplify/lib/python2.7/site-packages/molSimplify/Scripts/cellbuilder.py", line 604, in combine_multi_aligned_payload_with_cell
>     distorted_payload,enl = cell_ffopt('mmff94',distorted_payload,cand_list)
>   File "/home/chris/miniconda2/envs/molSimplify/lib/python2.7/site-packages/molSimplify/Scripts/cellbuilder_tools.py", line 55, in cell_ffopt
>     if atom.atomicnum in metals:
> AttributeError: 'OBAtom' object has no attribute 'atomicnum'

if I only select one atom to align it works without problem, so I guess it has something to do with the force-field, but selecting a different FF (-ff ..) does not help in this case. OBAtom should have the attribute atomicnum, so I am not sure what causes the problem here...

Thanks in advance for your help!

Chris

**Comment by jpjanet** [comment]
Hi Chris,

Thanks for pointing this out, and sorry for the delay - I was traveling in Feb. This is related to conversion from old Pybel sytnax to only using the openbabel API, and is fixed in [b1d6a41](https://github.com/hjkgrp/molSimplify/commit/b1d6a41f88b2a76235364428f8c88f0acb955d67), and I have updated the conda image. You can call `conda update -c hjkgroup molsimplify`. I tested this issue with a quick [MWE](https://github.com/jpjanet/SilverMWE). Please let know if you still have problems.
