### ISSUE TITLE
The number of ligand atoms of serial number 0 in connections_list is 0, resulting in an error.

### ISSUE THREAD

**Issue by cgarls** [hjkgrp/molSimplify#241]
When I was running RACs today, I found some CIF errors: molSimplify\Informatics\MOF\MOF_descriptors.py", line 312 lc_descriptor_df = pd.DataFrame(lc_descriptors_i,  columns=lc_names) ValueError: 0 columns passed, passed data had 96 columns;

After checking, I found that connections_list sequence number 0 ligand does not have atoms, resulting in failure to fire line 307
`if j == 0:`  , resulting in an error. 

Change it to `if lc_names == []: `to name the first non-zero ligand.

Do you decide if it is feasible? Can I ask you for a better solution?

**Comment by gianmarco-terrones** [comment]
Hi @cgarls, can you please upload the CIF that is causing the issue for `get_MOF_descriptors`?

**Comment by cgarls** [comment]
data_I
_chemical_name_common  'E:\D202110289\data_for_song\6.6_for_racs\example_MOF\cif/ACOGUV_no_solvent'
_cell_length_a 11.77300
_cell_length_b 15.14678
_cell_length_c 16.95490
_cell_angle_alpha 95.62350
_cell_angle_beta  90.00000
_cell_angle_gamma 112.86931
_space_group_name_H-M_alt      'P 1'


loop_
_space_group_symop_operation_xyz
  'x, y, z' 

loop_
_atom_site_label
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
_atom_site_type_symbol
C       0.0041   0.8854   0.9821     C
H       0.0064    0.936   0.6616     H
H     0.01028333   0.6872    0.034     H
C        0.017   0.7876   0.2864     C
C       0.0211    0.158    0.256     C
H       0.0366   0.0886   0.5352     H
H       0.0378   0.7462   0.3167     H
C       0.0385   0.2108   0.0005     C
C       0.0403   0.7524   0.0231     C
C       0.0499   0.1024   0.8045     C
H        0.052   0.0886   0.0352     H
C       0.0525   0.1024   0.3045     C
C       0.0685   0.8972   0.1965     C
H       0.0704    0.064   0.8384     H
H        0.094   0.2532   0.1754     H
C       0.1023   0.2138   0.7098     C
N       0.1027   0.8442   0.2423     N
C       0.1084   0.8456   0.7463     C
H       0.1094   0.7978   0.8542     H
C       0.1115   0.2138   0.2098     C
C       0.1187   0.1146   0.5179     C
H       0.1243     0.25   0.0055     H
H       0.1257     0.25   0.5055     H
C       0.1271   0.9406   0.9907     C
H       0.1275   0.9364   0.1631     H
C       0.1369    0.158    0.756     C
H       0.1513   0.9948   0.5219     H
H       0.1559   0.8932    0.638     H
H       0.1565   0.0052   0.9781     H
C       0.1584   0.8206   0.8102     C
H       0.1592   0.2532   0.6754     H
C       0.1657   0.8084   0.0318     C
C       0.1713   0.1028   0.3035     C
C       0.1723   0.2108   0.5005     C
C       0.1852   0.8762    0.684     C
C       0.1865   0.0594   0.5093     C
H       0.1911   0.0636   0.3369     H
C       0.2101   0.9052    0.017     C
C       0.2294   0.2124   0.2136     C
Zn     0.24937   0.6448  0.53035    Zn
C       0.2534   0.7634    0.052     C
N       0.2585   0.1558   0.2577     N
H       0.2627   0.1068    0.862     H
C       0.2628   0.1544   0.7537     C
O       0.2676   0.7072   0.9969     O
C       0.2789   0.8286   0.8102     C
C       0.2879   0.2476   0.4769     C
H       0.2916   0.2538   0.1833     H
C       0.3049   0.0948    0.483     C
C        0.305   0.8816   0.6894     C
Zn      0.3057   0.8539  0.24417    Zn
O       0.3087   0.7814   0.1158     O
C        0.309   0.1238    0.816     C
H       0.3109   0.8112    0.855     H
H       0.3116   0.2022   0.6458     H
O       0.3137   0.8804   0.3916     O
H     0.32308333   0.3128    0.466     H
C       0.3378   0.1794   0.6898     C
C       0.3455   0.9696   0.0265     C
C       0.3506   0.9686   0.3934     C
N        0.352   0.8592   0.7511     N
H       0.3546   0.9876   0.5164     H
H       0.3562   0.9026    0.646     H
C       0.3573   0.1916   0.4682     C
O       0.3618   0.9924   0.1686     O
H        0.367   0.0124   0.9836     H
O       0.3694   0.0076   0.3314     O
C       0.3759   0.0304   0.4735     C
C        0.382   0.0314   0.1066     C
H       0.3943    0.929   0.0202     H
Zn     0.39543   0.6448  0.03035    Zn
C       0.4234   0.1184   0.8106     C
O       0.4333   0.1196   0.1084     O
O       0.4396   0.7072   0.4969     O
C       0.4503   0.1714   0.6898     C
Zn      0.4518   0.1461  0.25583    Zn
H       0.4536   0.0974    0.854     H
H       0.4653    0.071   0.4798     H
O       0.4727   0.7814   0.6158     O
C         0.49   0.2366    0.448     C
N       0.4928   0.1408   0.7489     N
H       0.4997   0.1888    0.645     H
H       0.5003   0.8112    0.355     H
N       0.5072   0.8592   0.2511     N
C         0.51   0.7634    0.552     C
O       0.5273   0.2186   0.3842     O
H       0.5347    0.929   0.5202     H
H       0.5464   0.9026    0.146     H
Zn      0.5482   0.8539  0.74417    Zn
C       0.5497   0.8286   0.3102     C
O       0.5604   0.2928   0.5031     O
O       0.5667   0.8804   0.8916     O
C       0.5766   0.8816   0.1894     C
Zn     0.60457   0.3552  0.96965    Zn
H       0.6057    0.071   0.9798     H
C        0.618   0.9686   0.8934     C
C       0.6241   0.9696   0.5265     C
O       0.6306   0.9924   0.6686     O
H        0.633   0.9876   0.0164     H
O       0.6382   0.0076   0.8314     O
C       0.6427   0.8084   0.5318     C
H       0.6438   0.0974    0.354     H
H       0.6454   0.0124   0.4836     H
N        0.648   0.1408   0.2489     N
C       0.6494   0.0314   0.6066     C
C       0.6545   0.0304   0.9735     C
C       0.6622   0.8206   0.3102     C
H     0.67691667   0.6872    0.534     H
O       0.6863   0.1196   0.6084     O
H       0.6884   0.7978   0.3542     H
H       0.6891   0.1888    0.145     H
C        0.691   0.8762    0.184     C
O       0.6913   0.2186   0.8842     O
Zn      0.6943   0.1461  0.75583    Zn
C        0.695   0.1184   0.3106     C
C       0.6951   0.9052    0.517     C
H       0.7084   0.7462   0.8167     H
C       0.7121   0.7524   0.5231     C
C       0.7211   0.1714   0.1898     C
O       0.7324   0.2928   0.0031     O
C       0.7372   0.8456   0.2463     C
H       0.7373   0.8932    0.138     H
N       0.7415   0.8442   0.7423     N
C       0.7466   0.2366    0.948     C
Zn     0.75063   0.3552  0.46965    Zn
C       0.7706   0.7876   0.7864     C
C       0.7899   0.0948    0.983     C
H       0.8089   0.9364   0.6631     H
C       0.8135   0.9406   0.4907     C
C       0.8148   0.1238    0.316     C
C       0.8277   0.7892   0.4995     C
C       0.8287   0.8972   0.6965     C
C       0.8343   0.1916   0.9682     C
H       0.8408   0.7468   0.3246     H
C       0.8416   0.1794   0.1898     C
H       0.8435   0.9948   0.0219     H
H       0.8441   0.1068    0.362     H
H       0.8487   0.0052   0.4781     H
C       0.8631    0.842    0.244     C
H       0.8725   0.0636   0.8369     H
C       0.8729   0.0594   0.0093     C
H       0.8743     0.75   0.4945     H
H       0.8757     0.75   0.9945     H
C       0.8813   0.8854   0.4821     C
C       0.8885   0.7862   0.7902     C
H       0.8906   0.2022   0.1458     H
C       0.8916   0.1544   0.2537     C
N       0.8973   0.1558   0.7577     N
C       0.8977   0.7862   0.2902     C
H        0.906   0.7468   0.8246     H
H       0.9296    0.936   0.1616     H
C       0.9315   0.1028   0.8035     C
C       0.9475   0.8976   0.6955     C
H        0.948   0.9114   0.9648     H
C       0.9501   0.8976   0.1955     C
C       0.9597   0.2476   0.9769     C
C       0.9615   0.7892   0.9995     C
H       0.9622   0.2538   0.6833     H
H       0.9634   0.9114   0.4648     H
C       0.9789    0.842    0.744     C
C        0.983   0.2124   0.7136     C
H     0.98971667   0.3128    0.966     H
H       0.9936    0.064   0.3384     H
C       0.9959   0.1146   0.0179     C


Above is the CIF that reported the error, directly from the CSD database.

**Comment by gianmarco-terrones** [comment]
Regarding your question about solvent removal, yes molSimplify has a function that does this. 

Floating solvent detection in `molSimplify/Informatics/MOF/MOF_descriptors.py` is in the function `get_MOF_descriptors`. The code first computes the pairwise distance between every atom (taking into account the periodic nature of the cell) using the function `compute_distance_matrix3`. Next, an adjacency matrix is generated using these pairwise distances; the function that does this is `compute_adj_matrix`. The adjacency matrix indicates whether any two atoms are bonded, and this is determined both by the distance between the atoms and the elements that the atoms are. Following this, the connected subgraphs of the MOF are identified using the adjacency matrix. If there is a subgraph that does not contain a metal, we count that as floating solvent and featurization terminates. 

You can "clean" your structure of unbound solvent by using the function solvent_removal in `molSimplify/Informatics/MOF/PBC_functions.py`. There is a Jupyter notebook that goes through the process of feature generation for challenging CIF files: `molSimplify/Informatics/MOF/MOF_RAC_example.ipynb`.

**Comment by gianmarco-terrones** [comment]
Hi @cgarls, I am able to run `get_MOF_descriptors` on ACOGUV without issue. Are you using the most recent version of molSimplify? The commit SHA I am using is d51bd5015d1423e4e9d8da3d29d8f8d039358473. If you are using molSimplify as provided on Conda or pip, try using version 1.7.4

**Comment by cgarls** [comment]
Thank you for your reply, after trying the above procedure did solve my problem. I found that append is used for desc_dict in MOF_descriptors, but `append` is being deprecated in pandas. It is easy for a rookie like me to install a new version of pandas at the beginning of installation, so is it better to change to `concat`? After I modified three places, the higher version of pandas is also compatible.

**Comment by gianmarco-terrones** [comment]
Can you please indicate the error message you saw/what lines of the code are throwing the issue if a newer version of pandas is used?

**Comment by cgarls** [comment]
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_28333/3442337531.py in ?()
     11     if not os.path.exists(featurization_directory+'/primitive/'):
     12         os.mkdir(featurization_directory+'/primitive/')
     13     get_primitive(featurization_directory+'/cif/'+cif_file, featurization_directory+'/primitive/'+cif_file)
     14     #### With the primitive cells, we can generate descriptors and write them
---> 15     full_names, full_descriptors = get_MOF_descriptors(featurization_directory+'/primitive/'+cif_file,3,path=featurization_directory+'/',
     16         xyzpath=featurization_directory+'/xyz/'+cif_file.replace('cif','xyz'))
     17     full_names.append('filename')
     18     full_descriptors.append(cif_file)

~/anaconda3/envs/mols_1/lib/python3.10/site-packages/molSimplify/Informatics/MOF/MOF_descriptors.py in ?(data, depth, path, xyzpath, graph_provided, wiggle_room, max_num_atoms, get_sbu_linker_bond_info, surrounded_sbu_file_generation, detect_1D_rod_sbu)
   1179     For the cases that have a linker subgraph, do the featurization.
   1180     """""""""
   1181     if len(linker_subgraphlist)>=1: # Featurize cases that did not fail.
   1182         # try:
-> 1183             descriptor_names, descriptors, lc_descriptor_names, lc_descriptors = make_MOF_SBU_RACs(SBU_list, SBU_subgraphlist, molcif, depth, name, cell_v, anc_atoms, sbupath, linkeranchors_superlist, connections_list, connections_subgraphlist)
   1184             lig_descriptor_names, lig_descriptors = make_MOF_linker_RACs(linker_list, linker_subgraphlist, molcif, depth, name, cell_v, linkerpath, linkeranchors_superlist)
   1185             full_names = descriptor_names+lig_descriptor_names+lc_descriptor_names #+ ECFP_names
   1186             full_descriptors = list(descriptors)+list(lig_descriptors)+list(lc_descriptors)

~/anaconda3/envs/mols_1/lib/python3.10/site-packages/molSimplify/Informatics/MOF/MOF_descriptors.py in ?(SBUlist, SBU_subgraph, molcif, depth, name, cell_v, anchoring_atoms, sbupath, linkeranchors_superlist, connections_list, connections_subgraphlist)
    320         descriptors == list(descriptors)
    321         desc_dict = {key: descriptors[ii] for ii, key in enumerate(descriptor_names)}
...
   6297         ):
   6298             return self[name]
-> 6299         return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'append'
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...`

In addition, I would like to ask if the RACs I generated is 177 columns, and the RACs dimension in the paper is obviously higher than mine. May I ask if there are any parameters I chose wrong?

Code address of the paper:  https://github.com/aimat-lab/MOF_Synthesis_Prediction
`[MOF_Synthesis_Prediction](https://github.com/aimat-lab/MOF_Synthesis_Prediction/tree/main)/[code](https://github.com/aimat-lab/MOF_Synthesis_Prediction/tree/main/code)/[RAC_features](https://github.com/aimat-lab/MOF_Synthesis_Prediction/tree/main/code/RAC_features)/[temperature](https://github.com/aimat-lab/MOF_Synthesis_Prediction/tree/main/code/RAC_features/temperature)
/big.csv`

**Comment by gianmarco-terrones** [comment]
It seems you may be using an older version of the code. The error thrown appears to be in the function `make_MOF_SBU_RACs`, which should no longer call the function append on any pandas dataframes. The reason I think the code you are using is older is that the inputs to the last function in your error traceback seem almost identical to the inputs for `make_MOF_SBU_RACs`, but are missing the `Gval` argument.

Your number of RACs seems correct, assuming you have a column indicating the MOF name. Please see the attached screenshot:
<img width="536" alt="image" src="https://github.com/hjkgrp/molSimplify/assets/78051991/e9ed1654-c506-4bf7-91a9-aa90e8db150a">

Our group was not behind the MOF Synthesis Prediction paper. However, upon inspection of `code/RAC_features/temperature/ML_LR_GB_RF_GP_METAL_el_ox.py`, I see that they have a line `Preparing the input according to precomputed features by KULIK` and then a list of feature names. Some of those feature names are not RACs and are instead geometric information, e.g., ASA. Also, it seems they have 156 RAC features, and then have a version of the 156 RAC features with "sum" in the name for a total of 312 features. Not sure what is going on there.
