### ISSUE TITLE
PF3 mol file contains NF3 structure

### ISSUE THREAD

**Issue by fredauski** [hjkgrp/molSimplify#250]
Dear all, I just happened to notice that the ligand PF3 ([`phosphorustrifluoride.mol`](https://github.com/hjkgrp/molSimplify/blob/main/molSimplify/Ligands/phosphorustrifluoride.mol)) does not contain the correct structure:

```text
PF3 Phosphorus trifluoride 7783553
##CCCBDB 5172217:13
Geometry Optimized at CCSD(T)/6-31G*
  4  3  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.4923 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    1.2439   -0.1276 F   0  0  0  0  0  0  0  0  0  0  0  0
    1.0772   -0.6219   -0.1276 F   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0772   -0.6219   -0.1276 F   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0
  1  3  1  0  0  0
  1  4  1  0  0  0
M  END
```

**Comment by dbkchu** [comment]
Hi @fredauski,

Thank you for pointing this out! This was taken directly from the [NIST Computational Chemistry Comparison and Benchmark DataBase](https://cccbdb.nist.gov/geom3x.asp?method=12&basis=1&casno=7783553)... As you can see, the error is from there.I will email them about this, but in the meantime, you can [use SMILES](https://hjkgrp.mit.edu/tutorials/2018-05-09-molsimplify-tutorial-10-adding-ligands-molsimplify/) to build the PF3 ligand. 

I will also add a PF3 from SMILES to the database shortly.
