### ISSUE TITLE
Make Tensorflow/Kera an optional dependency

### ISSUE THREAD

**Issue by nhadler** [hjkgrp/molSimplify#256]
This might be a big ask, but it would be helpful if tensorflow/keras could be set as an optional dependency. Since it's not a required dependency for generating structures, it would shrink the installation time and cut down on package size when it's not needed, as well as avoiding incompatibilities when packaging molSimplify with other projects.

**Comment by gianmarco-terrones** [comment]
Hi @nhadler, the area where I see this being an issue is in `molSimplify/Scripts/structgen.py` (functions `mcomplex` and `init_ANN`), when an ANN is called to estimate M-L bond length if the metal is Fe, Mn, Cr, Co, or Ni (`molSimplify/Scripts/tf_nn_prep.py`). 

I also see that in `init_ANN` the code checks for `args.skipANN`, so you could try always setting that to True during complex construction (skipANN is a flag just like core or lig). Doing this, I think you could uninstall Tensorflow and Keras in your molSimplify environment without issue, with most of molSimplify functionality still working

**Comment by nhadler** [comment]
Hi @gianmarco-terrones, thanks for the quick response. Yeah, that totally works and it's what I do currently. Where that doesn't really work as well is when molSimplify is packaged as a dependency of another package---there's not an easy solution with pip to exclude specific packages when installing without ignoring all dependencies. Downstream this leads to a lot of bloat with building docker images or publishing to pip.

**Comment by gianmarco-terrones** [comment]
Thank you for the suggestions. I asked some other members of the Kulik Group, and we agreed that the ANN is an essential part of molSimplify, though it is true that the packages required for it are cumbersome. Making those packages optional would mean we would have to remove some test cases, which we want to keep to ensure the ANN is working properly. Is it possible for you to fork the repo and make a pip release without tensorflow and keras that you can use for your own projects?

**Comment by nhadler** [comment]
> Thank you for the suggestions. I asked some other members of the Kulik Group, and we agreed that the ANN is an essential part of molSimplify, though it is true that the packages required for it are cumbersome. Making those packages optional would mean we would have to remove some test cases, which we want to keep to ensure the ANN is working properly. Is it possible for you to fork the repo and make a pip release without tensorflow and keras that you can use for your own projects?

For the docker case, I ended up just manually installing the packages except for tensorflow and keras, and then installed molsimplify with pip using the `--no-deps` flag, which all worked in the end. Thanks for taking the time to consider the ask!
