### ISSUE TITLE
Structure Files Use Tab Separators on Columns

### ISSUE THREAD

**Issue by r-e-g-ular** [hjkgrp/molSimplify#272]
Structure files generated using molSimplify (mol3D.py?) separate coordinate columns with tabs rather than spaces. See: "writexyz" and "coord_string" functions with commands like  ss += "%s \t%f\t%f\t%f\n" % (atom.sym, xyz[0], xyz[1], xyz[2])", among others.

This behaviour is undesirable as:
1) It is inconsistent with other programs which generate structures (Avogadro, ASE).
2) It requires tab-space replacement before structure files can be used as input for certain calculators
(Orca requires coordinate columns to be space separated: https://orcaforum.kofo.mpg.de/viewtopic.php?f=11&t=11726&p=47766&hilit=xyz+syntax#p47766).

Suggested fix:
If possible, i.e. if structure files will still work with your calculator of choice (TeraChem?), replace tab insertion with insertion of 8 spaces.

**Comment by gianmarco-terrones** [comment]
Hi @r-e-g-ular, we just pushed a change that hopefully addresses your issue. Let us know how it works!

**Comment by gianmarco-terrones** [comment]
To use the flag with the `startgen_pythonic` geometry construction function, use code like the following:
```
from molSimplify.Scripts.generator import startgen_pythonic
input_dict = {'-core': 'ir', '-lig': 'h2o', '-ligocc': '6', '-oxstate': '3', '-geometry': 'oct', '-coord': '6', '-spin': '1', '-no_tabs': '0'}
# Value of the -no_tabs key does not matter
startgen_pythonic(input_dict=input_dict, write=True)
```

**Comment by r-e-g-ular** [comment]
@gianmarco-terrones This fix works beautifully. Thank you very much.
