### ISSUE TITLE
Possible scikit-learn dependency issue [installing through conda]

### ISSUE THREAD

**Issue by sweitzner** [hjkgrp/molSimplify#34]
Hello,

I encounter the error message below after installing molSimplify following the instructions listed here for a conda installation: http://hjkgrp.mit.edu/content/installing-molsimplify. Is the version of molSimplify installed through conda the most up to date release and is it installing the correct version of scikit-learn?

± molsimplify -i example-1.in
Using TensorFlow backend.
TensorFlow connection successful
WARNING:tensorflow:From /Users/weitzner1/opt/anaconda3/envs/molSimplify/lib/python3.6/site-packages/molSimplify/__main__.py:84: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From /Users/weitzner1/opt/anaconda3/envs/molSimplify/lib/python3.6/site-packages/molSimplify/__main__.py:84: The name tf.logging.ERROR is deprecated. Please use tf.compat.v1.logging.ERROR instead.

Input file detected, reading arguments from input file
molSimplify is starting!

************************************************************
******** Welcome to molSimplify! Let's get started. ********
************************************************************

Checking input...
swithcing core from ['cobalt'] to Co
building an equilibrium complex
loading ligand from dictionary: tpp
looking for /Users/weitzner1/opt/anaconda3/envs/molSimplify/lib/python3.6/site-packages/molSimplify/Ligands/tpp.mol
loading ligand from dictionary: imidazole
looking for /Users/weitzner1/opt/anaconda3/envs/molSimplify/lib/python3.6/site-packages/molSimplify/Ligands/imidazole.mol
loading ligand from dictionary: x
looking for /Users/weitzner1/opt/anaconda3/envs/molSimplify/lib/python3.6/site-packages/molSimplify/Ligands/x.mol
[False, '1']

Directory /Users/weitzner1/Codes/molSimplify/examples/Runs//co_oct_2_tpp_1_imidazole_1_x_1_s_1 already exists. Keep both (k), replace (r) or skip (s) k/r/s: r
Traceback (most recent call last):
  File "/Users/weitzner1/opt/anaconda3/envs/molSimplify/bin/molsimplify", line 11, in <module>
    sys.exit(main())
  File "/Users/weitzner1/opt/anaconda3/envs/molSimplify/lib/python3.6/site-packages/molSimplify/__main__.py", line 191, in main
    emsg = startgen(sys.argv, False, gui)
  File "/Users/weitzner1/opt/anaconda3/envs/molSimplify/lib/python3.6/site-packages/molSimplify/Scripts/generator.py", line 209, in startgen
    emsg = multigenruns(rundir, args, globs)
  File "/Users/weitzner1/opt/anaconda3/envs/molSimplify/lib/python3.6/site-packages/molSimplify/Scripts/rungen.py", line 316, in multigenruns
    emsg = rungen(rundir, args, fname, globs)
  File "/Users/weitzner1/opt/anaconda3/envs/molSimplify/lib/python3.6/site-packages/molSimplify/Scripts/rungen.py", line 620, in rungen
    args, rootdir, ligands, ligocc, globs, mcount)
  File "/Users/weitzner1/opt/anaconda3/envs/molSimplify/lib/python3.6/site-packages/molSimplify/Scripts/structgen.py", line 3887, in structgen
    strfiles, args, rootdir, ligands, ligoc, globs, sernum)
  File "/Users/weitzner1/opt/anaconda3/envs/molSimplify/lib/python3.6/site-packages/molSimplify/Scripts/structgen.py", line 3650, in structgen_one
    args, ligands, ligoc, licores, globs)
  File "/Users/weitzner1/opt/anaconda3/envs/molSimplify/lib/python3.6/site-packages/molSimplify/Scripts/structgen.py", line 2795, in mcomplex
    args, ligands, occs, dents, batslist, tcats, licores)
  File "/Users/weitzner1/opt/anaconda3/envs/molSimplify/lib/python3.6/site-packages/molSimplify/Scripts/structgen.py", line 148, in init_ANN
    from molSimplify.Scripts.tf_nn_prep import tf_ANN_preproc
  File "/Users/weitzner1/opt/anaconda3/envs/molSimplify/lib/python3.6/site-packages/molSimplify/Scripts/tf_nn_prep.py", line 14, in <module>
    from molSimplify.python_krr.sklearn_models import sklearn_supervisor
  File "/Users/weitzner1/opt/anaconda3/envs/molSimplify/lib/python3.6/site-packages/molSimplify/python_krr/sklearn_models.py", line 2, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib'

**Comment by adityanandy** [comment]
Hi there, 

Thanks for pointing this out to us. We will fix our conda image. In the meantime, you can use the installation instructions on our git page, where we have patched this!

Please feel free to let us know if you still have trouble with that.

Sincerely,
Aditya

**Comment by sweitzner** [comment]
Hi Aditya,

Thanks for the quick reply! 

By the way, is there a more advanced example you could point me towards that shows how to generate organometallic complexes using imported classes and scripts? I see that Prof. Kulik has an example posted on her tutorial page (http://hjkgrp.mit.edu/content/using-molsimplify-python-scripts, but this shows only basic functionality. I’m interested in building structures on the fly within a framework I’m developing. I am interested in essentially reproducing the behavior of the command line interface but within a script. I apologize if this has been asked elsewhere already.

Best,
Stephen

**Comment by adityanandy** [comment]
Hi Stephen,

No worries! If you are familiar with python, we have a way to do this using a function that is present at molSimplify.Scripts.generator --> the function is called startgen_pythonic. Basically, you can hand in a list of command line style arguments (you can see our tutorials for more details on that), and what you'll get back out is a mol3D class. This should help you generate structures in the method you are asking about. I'll give a quick example below:

startgen_pythonic({'-core': 'co', '-lig': 'carbonyl', '-ligocc': 6, '-geometry': 'oct'}) will get you an octahedral geometry with 6 carbonyl ligands. You can adjust any of these arguments based on your desired ligands / geometry to generate your geometries of interest. With respect to functions, we have also documented inputs in more detail here: https://molsimplify.readthedocs.io/en/latest/. This will get you more information on functions in our API that may be useful for geometric manipulation (e.g. measuring distances and angles, changing mol3D classes to increase bond lengths, etc.). 

Hope that's helpful for what you need.

Sincerely,
Aditya

**Comment by sweitzner** [comment]
Hi Aditya,

This is great, thank you. I will be sure to follow up if I encounter any more issues.

Best,
Stephen
