### ISSUE TITLE
Controlling the location of ligand placement

### ISSUE THREAD

**Issue by sweitzner** [hjkgrp/molSimplify#35]
Hello,

Is it possible to control the location of specific ligands in the presence of multiple ligand types? I am interested in enumerating symmetrically unique configurations for a complex with two or more different ligands but I cannot seem to find the right input for startgen_pythonic. I have been able to control the location to some extent, but the requested binding site on the molecule (which I am passing in from a SMILES string and attempting to choose the carboxyl group) is applied to the first molecule, but not to the second, leading to strange configurations.

For example, this input 
```python
    smiles = "C1=CSC(=C1)C(=O)O"
    input_dict = {
        '-core'    : 'Cu',
        '-coord'   : '6',
        '-geometry': 'oct',
        '-spin'    : '1',
        '-oxstate' : '2',
        '-skipANN' : 'True',
        '-smicat'  : '8',
        '-keepHs'  : 'no,yes',
        '-lig'     : f'{smiles},water',
        '-ligocc'  : '2,4'
    }
```
leads to this particular geometry:
![image](https://user-images.githubusercontent.com/3386582/97246539-f7ed6280-17d3-11eb-8e04-80fcf838b26f.png)
but if I try to force the ligand to the other side (with perhaps an incorrect input dict) using:
```python
    smiles = "C1=CSC(=C1)C(=O)O"
    input_dict = {
        '-core'    : 'Cu',
        '-coord'   : '6',
        '-geometry': 'oct',
        '-spin'    : '1',
        '-oxstate' : '2',
        '-skipANN' : 'True',
        '-smicat'  : '8',
        '-keepHs'  : 'no,yes,no',
        '-lig'     : f'{smiles},water,{smiles},water',
        '-ligocc'  : '1,1,1,3'
    }
```
I obtain this strange configuration:
![image](https://user-images.githubusercontent.com/3386582/97246798-95e12d00-17d4-11eb-8dd9-e8550460e978.png)
I was hoping if somebody could let me know if this is a bug or just user error? Are there methods already available to do the type of structure enumeration I am attempting here?

Thanks,
Stephen

**Comment by adityanandy** [comment]
Hi Stephen, 

Did you try using the keyword `-ligloc: True`? This should give you the expected behavior for what you're asking for. This will place ligands first in the equatorial plane, and then in the axial plane, in the order you hand in the -lig flag.

**Comment by adityanandy** [comment]
Also, the thing you are looking for is the argument `-smicat`. This stands for smiles connecting atom. It is a 1-indexed list, where you can hand it the list of your coordinating atom.

**Comment by sweitzner** [comment]
Setting `-ligloc: True` with this input
```python
    input_dict = {
        '-core'    : 'Cu',
        '-coord'   : '6',
        '-geometry': 'oct',
        '-spin'    : '1',
        '-oxstate' : '2',
        '-skipANN' : 'True',
        '-smicat'  : '8',
        '-keepHs'  : 'no,yes,no',
        '-lig'     : f'{smiles},water,{smiles},water',
        '-ligocc'  : '1,1,1,3',
        '-ligloc'  : 'True'
    }
```
still leads to this structure:
![image](https://user-images.githubusercontent.com/3386582/97247593-5b788f80-17d6-11eb-95fc-33121951c048.png)
but if I replace my smicat string with the syntax you mentioned fixes my connectivity problem:
```python
    input_dict = {
        '-core'    : 'Cu',
        '-coord'   : '6',
        '-geometry': 'oct',
        '-spin'    : '1',
        '-oxstate' : '2',
        '-skipANN' : 'True',
        '-smicat'  : '[8],[8]',
        '-keepHs'  : 'no,yes,no',
        '-lig'     : f'{smiles},water,{smiles},water',
        '-ligocc'  : '1,1,1,3'
    }
```
![image](https://user-images.githubusercontent.com/3386582/97247662-7ba84e80-17d6-11eb-9a54-3ad851357ff5.png)

Thanks! Does MolSimplify currently have a function for generating symmetrically unique configurations? If not I can manage, but there I figured that I would double check so as to not have to reinvent the wheel.

Thanks again, Aditya.

**Comment by adityanandy** [comment]
Hi Stephen,

Sorry, I responded to your question too fast! Smicat was the one I was going for, with the list of lists format. molSimplify currently doesn't have built-in tools to enumerate configurations. We typically do that externally to molSimplify using for loops (checking for isomers), when we need to. Hope that helps! I'll close this request, feel free to open a new one if something else comes up.

Sincerely,
Aditya
