### ISSUE TITLE
Installing to existing conda env

### ISSUE THREAD

**Issue by puckvg** [hjkgrp/molSimplify#36]
Hi there, 

Forgive my ignorance as I'm not a conda expert, but I'm trying to add your package to an existing conda environment. I tried `conda env update --file mols.yml` but because there's a name defined in the yml file it creates a new environment anyway. I then tried to manually install the dependencies in the yml file and pip install from the molSimplify directory as suggested in the instructions, but 9 tests fail: 
```
FAILED tests/test_bidentate.py::test_bidentate - ValueError: Inpu...
FAILED tests/test_example_1.py::test_example_1 - ValueError: Inpu...
FAILED tests/test_example_1.py::test_example_1_No_FF - ValueError...
FAILED tests/test_example_5.py::test_example_5 - ValueError: Inpu...
FAILED tests/test_example_7.py::test_example_7 - ValueError: Inpu...
FAILED tests/test_molcas_caspt2.py::test_molcas_caspt2 - ValueErr...
FAILED tests/test_molcas_casscf.py::test_molcas_casscf - ValueErr...
FAILED tests/test_orca_ccsdt.py::test_orca_ccsdt - ValueError: In...
FAILED tests/test_orca_dft.py::test_orca_dft - ValueError: Input ...
```

Could I get some help as to how to safely install your package to an existing conda env? 
Thanks, 
Puck

**Comment by chenruduan** [comment]
Hi Puck, 

Some of the packages need to be installed by conda (not pip). But before I provide any more help, could you send me the packages info of the env that you tried to install molSimplify and the env that you currently have (after your attempt of installing bey yourself)? You can check the packages info by `conda list` in an env.

**Comment by adityanandy** [comment]
Closing this issue to due to inactivity. Feel free to reopen if issues still exist.
