### ISSUE TITLE
Git Tags for releases 

### ISSUE THREAD

**Issue by jan-janssen** [hjkgrp/molSimplify#37]
I noticed that the latest git tag is pointing to version 1.1.48 while the conda package is build for 1.5.0. Can you create a git tag for 1.5.0 ?

**Comment by gianmarco-terrones** [comment]
Hi @jan-janssen, we have made a new version (https://github.com/hjkgrp/molSimplify/releases/tag/v1.6.0) with a corresponding conda 1.6.0 package (https://anaconda.org/hjkgroup/molsimplify/files), will that work for you?

**Comment by jan-janssen** [comment]
Is there a specific reason why you do not use the `conda-forge` ?

**Comment by gianmarco-terrones** [comment]
Nope! Our group started using `conda` a few years ago and it was more convenient to keep everything in `conda`.

**Comment by adityanandy** [comment]
Closing this request now since we updated. Jan -- please feel free to re-open if you have further concerns. Thanks!
