### ISSUE TITLE
CentOS on docker

### ISSUE THREAD

**Issue by tatsuya-takakuwa** [hjkgrp/molSimplify#45]
I have mol simplify installed in Docker's cent8 environment with the aim of using it with terachem. However, even if I start the molsimplify command, a core dump occurs. How is it used in combination with terateam?

**Comment by adityanandy** [comment]
Can you please provide more details of your issue? For instance screenshots, or confirming that you did a docker install of molSimplify? We typically would install molsimplify and use it to build structures and write input files, and use terachem to run those calculations with the inputs written by molSimplify

**Comment by tatsuya-takakuwa** [comment]
![キャプチャ](https://user-images.githubusercontent.com/57566373/147205144-8bfea122-ab5c-4a64-b023-e5483857fab1.PNG)
[config.txt](https://github.com/hjkgrp/molSimplify/files/7767576/config.txt)

I am also thinking of using Terachem and molsimplify together.
Docker is created by creating a DockerFile from the Cuda distribution image.
I'm not using the molsimplify image from Docker hub. (It is configured in python2, and I was concerned about compatibility with programs created in python3.)
I pulled the Config from Docker Inspect for reference.
If you run the command molsimplify as shown in the screenshot, it will do a CoreDump.

Thank you very much for your help.
