### ISSUE TITLE
Segmentation fault (core dumped) error

### ISSUE THREAD

**Issue by ClinicalAI** [hjkgrp/molSimplify#50]
Hi,
I used conda to install molsimlify. It seems it is installed successfully and when I run the test, all test passed successfully. But when I want to run molsimplify command I got the following error:

Segmentation fault (core dumped)

**Comment by adityanandy** [comment]
Hi! Can you give us a little bit more information? What is the OS of the system you are running, and can you provide a screenshot of the stack trace before the seg fault? That way we can help figure out what exactly went wrong! Thanks!

**Comment by ClinicalAI** [comment]
Hi,
Here are some info:

OS:
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"

Python version:
Python 3.6.8 

gcc version:
gcc version 9.3.0 

Here is a screenshot:
![image](https://user-images.githubusercontent.com/96053939/151500159-b14977a0-35b6-46cd-9e85-7c27f47f51e8.png)

All the test passed, but when I run molsimplify I see only "Segmentation fault (core dumped)". There is no stack  trace unfortunately!

I used the instruction you provide in Github to install the molsimplify:
https://github.com/hjkgrp/molSimplify

**Comment by adityanandy** [comment]
Hi, this is because it is trying to open the GUI --> the GUI is not tested / guaranteed to work on ubuntu. Can you try using the commandline interface (e.g. molsimplify -core fe) and get back to us here if that also does not work? Thanks!

**Comment by ClinicalAI** [comment]
Thanks, molsimplify -core fe also shows the same error.

**Comment by adityanandy** [comment]
Thanks for your response. One more test to try: `molsimplify -core fe -skipANN true` --> can you let us know if that also produces the error? Thanks!

**Comment by adityanandy** [comment]
Closing this request due to lack of response. Feel free to open back up and let us know if this error persists, and we'll follow up.
