### ISSUE TITLE
ligands.dict charge assignment for xyz files

### ISSUE THREAD

**Issue by gianmarco-terrones** [hjkgrp/molSimplify#70]
When using molSimplify from the command line, the generated `terachem_input` files do not have the correct charge if the ligand is not neutral and uses an xyz file as its geometry in `ligands.dict`.

**Comment by adityanandy** [comment]
@gianmarco-terrones as a comment on this --> ligands should generally not be stored in the ligands dict as XYZs, but rather as .mol files, which store charge. But I agree this is worth adjusting...

**Comment by gianmarco-terrones** [comment]
Resolved! Now using xyz files in ligands.dict works even if the ligands that use the xyz files as geometries are not neutral. Verified that the `terachem_input` generated has the correct charge by running `molsimplify -core iron -geometry oct -lig ooh -oxstate 2 -spin 1`. Before, this had the line `charge 2`. Now, it gives the correct charge of `charge -4`. ooh uses an xyz as its geometry in ligands.dict and has a charge of -1.
