### ISSUE TITLE
∆E_H-L from a xyz file

### ISSUE THREAD

**Issue by DavidRamirezPalma** [hjkgrp/molSimplify#82]
Hi,
I'm trying to get the value of ∆E_H-L of a complex from an xyz file (included at the end). The command line I use is the following:

molsimplify -core DPL424BT.xyz -geometry oct -coord 6 -oxstate II -spin 5

However, I get an error in the process. I guess the error is due to the fact that I did not enter the information of the ligand correctly but I do not know how to do it since the complex has two bidentate ligands and two monodentate ligands.

How can I get the properties with molSimplify from a complex with bidentate ligands (or higher) in an xyz file?

Any help with this or advice is appreciated. 
Best,
David

***************************************************

63
DPL424BT
Se      7.527825    7.028065    6.006982
Fe     10.153138    3.855600    8.676598
N       9.198281    4.477894   10.536861
C       9.064387    5.774147   10.857895
H       9.393165    6.425589   10.250359
N       8.627933    4.876563    7.645818
C       8.476816    6.204432   12.015353
H       8.406345    7.132528   12.205683
S       8.733284    1.761469    9.277019
C       8.830065    2.117496   11.050515
H       9.694733    1.781881   11.393102
H       8.110112    1.617871   11.511676
C       8.705225    3.574141   11.402785
C       7.989811    5.274461   12.893425
H       7.585479    5.546381   13.708921
C       8.096909    3.945821   12.581067
H       7.755300    3.285796   13.171267
C       6.987753    2.193836    8.945573
H       6.859245    3.163990    9.097101
H       6.781861    2.006138    7.994999
C       8.186079    5.722482    7.017633
C       5.837698    0.087137    9.622347
H       6.299588   -0.369066    8.928775
C       6.042085    1.436597    9.808026
C       5.356393    2.072771   10.828394
H       5.480458    3.004345   10.964634
C       4.961683   -0.609956   10.439683
H       4.828280   -1.540659   10.305248
C       4.497564    1.376449   11.645730
H       4.052218    1.824894   12.354782
C       4.285760    0.041640   11.442698
H       3.673172   -0.433662   11.992655
Se     12.778451    0.683135   11.346214
N      11.107995    3.233306    6.816335
C      11.241889    1.937053    6.495301
H      10.913111    1.285611    7.102837
N      11.678343    2.834637    9.707378
C      11.829460    1.506768    5.337843
H      11.899931    0.578672    5.147513
S      11.572992    5.949731    8.076177
C      11.476211    5.593704    6.302681
H      10.611543    5.929319    5.960094
H      12.196164    6.093329    5.841520
C      11.601051    4.137059    5.950411
C      12.316465    2.436739    4.459771
H      12.720797    2.164819    3.644275
C      12.209367    3.765379    4.772129
H      12.550976    4.425404    4.181929
C      13.318523    5.517364    8.407624
H      13.447031    4.547210    8.256095
H      13.524415    5.705062    9.358197
C      12.120197    1.988718   10.335564
C      14.468578    7.624063    7.730849
H      14.006687    8.080266    8.424421
C      14.264191    6.274603    7.545170
C      14.949883    5.638429    6.524802
H      14.825818    4.706855    6.388562
C      15.344593    8.321156    6.913513
H      15.477996    9.251859    7.047949
C      15.808712    6.334751    5.707466
H      16.254058    5.886306    4.998415
C      16.020516    7.669560    5.910499
H      16.633104    8.144862    5.360541

**Comment by ralf-meyer** [comment]
Hi @DavidRamirezPalma,

The simplest way to get the ML prediction of ∆E_H-L is to separate your xyz file into a core and a ligand part (in this case converted to smiles strings):

`molsimplify -core Fe -lig "n1ccccc1CSCc1ccccc1,N#C[Se]" -smicat "[[1,8], [1]]" -ligocc 2,2 -ligloc True -geometry oct -coord 6 -oxstate II -spin 5`

where `-smicat` defines the connecting atoms in the two ligands, `-ligocc` requests two copies of each ligand, and `ligloc` locks the locations of the ligands to constrain the first two ligands to the equatorial plane.

The resulting ML prediction is:
```
******************************************************************
************** ANN is engaged and advising on spin ***************
************** and metal-ligand bond distances    ****************
******************************************************************
You have selected a high-spin state, multiplicity = 5
('delta is', array([-9.39487635]), ' spin is ', True)
ANN predicts a spin splitting (HS - LS) of -9.39 kcal/mol at 20% HFX
ANN low spin bond length (ax1/ax2/eq) is predicted to be: 2.15 /2.02 /2.25 angstrom
ANN high spin bond length (ax1/ax2/eq) is predicted to be: 2.11 /1.99 /2.44 angstrom
distance to splitting energy training data is 13.61
ANN results are too far from training data, be cautious 
ANN predicts a HOMO value of -14.46 eV at 20% HFX
ANN predicts a LUMO-HOMO energetic gap value of 4.42 eV at 20% HFX
ANN results should be trustworthy for this complex 
distance to HOMO training data is 0.99
distance to GAP training data is 0.49
*******************************************************************
************** ANN complete, saved in record file *****************
*******************************************************************
```
Note the warning about the distance from (energy splitting) training data, i.e. the ∆E prediction is not very trustworthy.

Does this workflow work for you or do you need to predict the spin splitting from your xyz file? That might be easier by writing a short Python script to access the ML prediction directly.

**Comment by DavidRamirezPalma** [comment]
Thank you very much for your help. At the moment this solution works for me, however soon I would like to do these tests to a set of complexes (in xyz files from electronic structure calculations). I checked "Tutorial 11: Using molSimplify in Python scripts" and I guess this would have to do with my xyz file, but how can I get the ∆E_H-L with a python script? (because the tutorial is focused on geometry comparison). Thanks in advance.
Best,
David.

**Comment by ralf-meyer** [comment]
AFAIK reading (and constructing a graph) from a xyz file is currently not supported. Even if you decide to write a custom python script it will require some workarounds. I will try to construct a simple example script for you!
