### ISSUE TITLE
mol3D metal list

### ISSUE THREAD

**Issue by ralf-meyer** [hjkgrp/molSimplify#86]
I am looking for input how we should resolve the following bug I found:

`mol3D` keeps track of indices of metal atoms in the list `self.metals`. It appears that this was renamed from `self.metal`. The issue is that several methods including `addAtom()`, `deleteatom()`, and `convert2mol3D` still reset `self.metal` instead of the newer `self.metals`.

Proposed options to fix this:
- Replace all occurrences of `self.metal` with `self.metals`.
- Remove both `self.metal` and `self.metals` and only use `self.findMetal()` (recomputed every time) in all external calls (already the case according to my IDE).
- Properly implement `mol3D.metal` as read only property (see e.g. https://realpython.com/python-property/#providing-read-only-attributes)

Minimal test case showing the current problem:
```
from molSimplify.Classes.mol3D import mol3D
from molSimplify.Classes.atom3D import atom3D


def test_adding_and_deleting_atoms():
    mol = mol3D()
    mol.addAtom(atom3D(Sym='Fe'))

    assert mol.natoms == 1
    assert mol.findMetal() == [0]

    mol.addAtom(atom3D(Sym='Cu'))

    assert mol.natoms == 2
    assert mol.findMetal() == [0, 1]

    mol.deleteatom(0)

    assert mol.natoms == 1
    assert mol.findMetal() == [0]
```

**Comment by ralf-meyer** [comment]
PR #85 implements solution 1 as a quick and easy fix for this issue. There are, however, still ways to trigger the issue. For example:
```
mol = mol3D()
mol.addAtom(atom3D(Sym='Fe'))
assert mol.findMetal() == [0]

mol.atoms[0].mutate('C')
# Will fail:
assert mol.findMetal() == []
```

**Comment by gianmarco-terrones** [comment]
@ralf-meyer Your plan from June 29 sounds good to me. @dbkchu @adityanandy do y'all have any opinion?

**Comment by adityanandy** [comment]
no strong opinions from me. I think what Ralf said in sol'n 1 is good

**Comment by ralf-meyer** [comment]
I will close this for now and try to solve the remaining issues by introducing some (breaking) changes in the upcoming version 2
