### ISSUE TITLE
Generate haptic bond with molsimplify

### ISSUE THREAD

**Issue by taew0361** [hjkgrp/molSimplify#92]
Dear all
I tried to generate the structure of complex with haptic bond such as ferrocene with the following input

#input for ferrocene
-coord 2
-core Fe
-ligocc 2
-geometry li
-spin 0
-oxstate II
-lig [CH]1[CH][CH][CH][CH]1

However, the rings align vertically. 

I expect that this alignment comes from the intrinsic force field to maximize the COM.

Is there any way to generate the intial haptic bond using molsimplify?

Best regards

**Comment by dbkchu** [comment]
Currently, I believe molSimplify does not have excellent support for haptic bonds. I think the reason the rings align vertically here is actually that molSimplify assumes the first atom of the SMILES string is the coordinating atom unless you pass the `smicat` keyword. You can get a structure with the correct type of orientation by telling molSimplify to coordinate with two atoms from each ring in a square planar geometry:
```
-coord 4
-core Fe
-ligocc 2
-geometry sqp
-spin 0
-oxstate II
-lig [CH]1[CH][CH][CH][CH]1
-smicat 1,5
```
However, I do not think that the initial guess for the geometry will be very good. If you want to use ferrocene specifically as a base, we have a tutorial for functionalizing ferrocene [here](http://hjkgrp.mit.edu/tutorials/2016-12-25-molsimplify-tutorial-3-custom-core-functionalization/).

**Comment by gianmarco-terrones** [comment]
Hi @taew0361, `-core ferrcore` is what you'll want to use

**Comment by gianmarco-terrones** [comment]
Alternatively, you can git pull the latest molSimplify version from GitHub and run something like the following in the command line: `molsimplify -core Fe -geometry li -lig benzene_pi -oxstate 2 -ligocc 2 -spin 0 -coord 2`. 

To specify your own custom ligands that bond through an aromatic ring, I would recommend making a new entry in molSimplify/Ligands/ligands.dict rather than using a SMILES string, since in ligands.dict you can specify `pi` in the connecting atoms, and that will trigger bonding with the aromatic ring rather than with specific atoms. See for example the line for benzene_pi. You should set force field to N in the ligands.dict entry for your ligand as well.

**Comment by taew0361** [comment]
Hi @Gianmarco Terrones, thanks for providing the command line about aromatic ring

The desired ferrocene structure is generated by the following command line:
`molsimplify -core Fe -geometry li -lig cyclopentadienyl -oxstate 2 -ligocc 2 -spin 0 -coord 2 -MLbonds 3`

In addition, I ask the examples (command line) for the following complex cases

1) Ligands have two aromatic rings, and haptic bonding is specified in the one ring

![image](https://user-images.githubusercontent.com/105839531/187584610-d26a921e-7b93-40af-b843-1adac2c69285.png)

2) Two aromatic rings make haptic bonding like bidendate

![image](https://user-images.githubusercontent.com/105839531/187584528-797231e8-73c6-4fd4-a8ef-8030a44d61bc.png)

3) Complex that have more than 2 core metals 

![image](https://user-images.githubusercontent.com/105839531/187584661-92e6e765-63e6-4e2f-9e35-3e8790f51228.png)

**Comment by gianmarco-terrones** [comment]
@taew0361 Steps will look like this:

- Download Avogadro if you haven't already
- Generate the desired ligands with Avogadro, like that benzene ring joined to the five membered aromatic ring with the methyl group
- Save as an XYZ file
- Place XYZ file in the `molSimplify/Ligands` folder
- Add an entry for your new ligand in the file `molSimplify/Ligands/ligands.dict`, where the connection atoms are the indices (zero-indexed) of the atoms of the connecting aromatic ring and the word "pi". Also should refer to the XYZ file you just placed in the Ligands folder
- Say your new ligand is called myLigA in ligands.dict. Run a command like `molsimplify -core Zr -geometry thd -lig myLigA Cl -oxstate 2 -ligocc 2 2 -spin 0 -coord 4`. Currently a somewhat wonky structure results; we hope to look into this eventually

By the way, supported geometries are at `/molSimplify/molSimplify/Data/coordinations.dict`

I do not think molSimplify currently supports ligands that haptically bond through more than one aromatic ring, nor complexes with multiple metals. But I can imagine work arounds; for example for your complex 2 you could draw in the connection between the two axial ligands in Avogadro after molSimplify complex generation, and for complex 3 you could copy and paste half of the complex in Avogadro and merge two of them together. 

@dbkchu Does this all sound logical to you?

**Comment by gianmarco-terrones** [comment]
@dbkchu @taew0361 Closing the issue for now
