### ISSUE TITLE
Custom SMILES ligand naming not working as expected

### ISSUE THREAD

**Issue by O2-AC** [hjkgrp/molSimplify#93]
I am trying to use the `-sminame` option to give a custom ligand name for the folder creation, e.g. to avoid having folder names with "smiX" in them. However, using the option does not have any effect on the folder naming.

Example with `-sminame test`:

actual resulting folder name: `<core>_<geom>_<ox>_smi1_<ligocc>_s_<spin>`
expected resulting folder name: `<core>_<geom>_<ox>_test_<ligocc>_s_<spin>`

Could you clarify, if the folder name should have changed the way I expected it?

**Comment by gianmarco-terrones** [comment]
Hi, can you please give us the full command line argument you ran for molSimplify structure generation?

**Comment by O2-AC** [comment]
Sure. I used the following command:
```
molsimplify -core zncat -ccatoms 4,5 -lig NCCCN -ligocc 1 -smicat "1,5" -replig true -oxstate II -spin 1 -geometry tbp -sminame testname
```
This will create the following:
```
.
├── CLIinput.inp
└── Runs
    └── zncat_tbp_2_smi1_1_s_1
        └── zncat_tbp_2_smi1_1_s_1_conf_1
            ├── jobscript
            ├── terachem_input
            ├── zncat_tbp_2_smi1_1_s_1_conf_1.molinp
            ├── zncat_tbp_2_smi1_1_s_1_conf_1.report
            └── zncat_tbp_2_smi1_1_s_1_conf_1.xyz
```
Instead of the expected:
```
.
├── CLIinput.inp
└── Runs
    └── zncat_tbp_2_testname_1_s_1
        └── zncat_tbp_2_testname_1_s_1_conf_1
            ├── jobscript
            ├── terachem_input
            ├── zncat_tbp_2_testname_1_s_1_conf_1.molinp
            ├── zncat_tbp_2_testname_1_s_1_conf_1.report
            └── zncat_tbp_2_testname_1_s_1_conf_1.xyz
```

**Comment by dbkchu** [comment]
From what I can tell, it looks like this is supposed to have the expected effect, except that it should only keep the first three letters of the `-sminame` argument (as seen [here](https://github.com/hjkgrp/molSimplify/blob/af9b751ba2dc9e85bb3eb35b154348c3607dff1e/molSimplify/Scripts/rungen.py#L462)). However, it seems that fe487c5 broke this functionality ~6 years ago. We need to look through and fix the `name_complex` function [here](https://github.com/hjkgrp/molSimplify/blob/af9b751ba2dc9e85bb3eb35b154348c3607dff1e/molSimplify/Scripts/io.py#L948).

I can do it later this week if no one else wants to take this up.

**Comment by gianmarco-terrones** [comment]
@O2-AC @dbkchu Should be fixed now, let me know!

**Comment by O2-AC** [comment]
The branch `iss-93-sminame` fixes the problem and takes the full name passed to `-sminame` for the directory naming.

Command:
```
molsimplify -core zncat -ccatoms 4,5 -lig NCCCN -ligocc 1 -smicat "1,5" -replig true -oxstate II -spin 1 -geometry tbp -sminame testname
```` 

Result
```
.
├── CLIinput.inp
└── Runs
    └── zncat_tbp_2_testname_1_s_1
        └── zncat_tbp_2_testname_1_s_1_conf_1
            ├── jobscript
            ├── terachem_input
            ├── zncat_tbp_2_testname_1_s_1_conf_1.molinp
            ├── zncat_tbp_2_testname_1_s_1_conf_1.report
            └── zncat_tbp_2_testname_1_s_1_conf_1.xyz
```
